import React, { createContext, useContext, useReducer, useEffect } from 'react';
import { Tenant, RentLog, RentCollector, AppSettings } from '../types';
import { loadFromStorage, saveToStorage } from '../utils/storage';

interface AppState {
  tenants: Tenant[];
  rentLogs: RentLog[];
  rentCollectors: RentCollector[];
  settings: AppSettings;
}

type AppAction =
  | { type: 'SET_TENANTS'; payload: Tenant[] }
  | { type: 'ADD_TENANT'; payload: Tenant }
  | { type: 'UPDATE_TENANT'; payload: Tenant }
  | { type: 'DELETE_TENANT'; payload: string }
  | { type: 'SET_RENT_LOGS'; payload: RentLog[] }
  | { type: 'ADD_RENT_LOG'; payload: RentLog }
  | { type: 'UPDATE_RENT_LOG'; payload: RentLog }
  | { type: 'DELETE_RENT_LOG'; payload: string }
  | { type: 'SET_RENT_COLLECTORS'; payload: RentCollector[] }
  | { type: 'ADD_RENT_COLLECTOR'; payload: RentCollector }
  | { type: 'DELETE_RENT_COLLECTOR'; payload: string }
  | { type: 'UPDATE_SETTINGS'; payload: AppSettings }
  | { type: 'WIPE_ALL_DATA' }
  | { type: 'LOAD_DUMMY_DATA' };

const initialState: AppState = {
  tenants: [],
  rentLogs: [],
  rentCollectors: [],
  settings: {
    defaultUnitPrice: 8,
  },
};

const AppContext = createContext<{
  state: AppState;
  dispatch: React.Dispatch<AppAction>;
} | null>(null);

function appReducer(state: AppState, action: AppAction): AppState {
  switch (action.type) {
    case 'SET_TENANTS':
      return { ...state, tenants: action.payload };
    case 'ADD_TENANT':
      return { ...state, tenants: [...state.tenants, action.payload] };
    case 'UPDATE_TENANT':
      return {
        ...state,
        tenants: state.tenants.map(t => t.id === action.payload.id ? action.payload : t),
      };
    case 'DELETE_TENANT':
      return {
        ...state,
        tenants: state.tenants.filter(t => t.id !== action.payload),
        rentLogs: state.rentLogs.filter(log => log.tenantId !== action.payload),
      };
    case 'SET_RENT_LOGS':
      return { ...state, rentLogs: action.payload };
    case 'ADD_RENT_LOG':
      return { ...state, rentLogs: [...state.rentLogs, action.payload] };
    case 'UPDATE_RENT_LOG':
      return {
        ...state,
        rentLogs: state.rentLogs.map(log => log.id === action.payload.id ? action.payload : log),
      };
    case 'DELETE_RENT_LOG':
      return {
        ...state,
        rentLogs: state.rentLogs.filter(log => log.id !== action.payload),
      };
    case 'SET_RENT_COLLECTORS':
      return { ...state, rentCollectors: action.payload };
    case 'ADD_RENT_COLLECTOR':
      return { ...state, rentCollectors: [...state.rentCollectors, action.payload] };
    case 'DELETE_RENT_COLLECTOR':
      return {
        ...state,
        rentCollectors: state.rentCollectors.filter(c => c.id !== action.payload),
      };
    case 'UPDATE_SETTINGS':
      return { ...state, settings: action.payload };
    case 'WIPE_ALL_DATA':
      return initialState;
    case 'LOAD_DUMMY_DATA':
      return {
        ...state,
        ...generateDummyData(),
      };
    default:
      return state;
  }
}

function generateDummyData(): Partial<AppState> {
  const dummyCollectors: RentCollector[] = [
    { id: '1', name: 'John Doe', createdAt: new Date().toISOString() },
    { id: '2', name: 'Jane Smith', createdAt: new Date().toISOString() },
    { id: '3', name: 'Mike Johnson', createdAt: new Date().toISOString() },
    { id: '4', name: 'Sarah Wilson', createdAt: new Date().toISOString() },
  ];

  const dummyTenants: Tenant[] = [
    {
      id: '1',
      name: 'Priya Sharma',
      propertyName: 'Sunrise Apartment 2A',
      propertyType: 'residential',
      monthlyRent: 15000,
      securityDeposit: 30000,
      startDate: '2024-01-01',
      startMeterReading: '1250',
      phoneNumber: '+919876543210',
      notes: 'Long-term tenant, always pays on time. Works as a software engineer.',
      documents: [],
      createdAt: new Date().toISOString(),
      isArchived: false,
    },
    {
      id: '2',
      name: 'Rajesh Kumar',
      propertyName: 'Garden View 1B',
      propertyType: 'residential',
      monthlyRent: 12000,
      securityDeposit: 24000,
      startDate: '2024-02-15',
      startMeterReading: '980',
      phoneNumber: '+919876543211',
      notes: 'Young professional, prefers digital payments. Works in marketing.',
      documents: [],
      createdAt: new Date().toISOString(),
      isArchived: false,
    },
    {
      id: '3',
      name: 'Anjali Patel',
      propertyName: 'Ocean View 3C',
      propertyType: 'residential',
      monthlyRent: 18000,
      securityDeposit: 36000,
      startDate: '2024-03-01',
      startMeterReading: '1450',
      phoneNumber: '+919876543212',
      notes: 'Family with kids, very reliable. Husband works in IT, wife is a teacher.',
      documents: [],
      createdAt: new Date().toISOString(),
      isArchived: false,
    },
    {
      id: '4',
      name: 'Vikram Singh',
      propertyName: 'City Center 4D',
      propertyType: 'commercial',
      monthlyRent: 22000,
      securityDeposit: 44000,
      startDate: '2024-04-10',
      startMeterReading: '2100',
      phoneNumber: '+919876543213',
      notes: 'Business professional, travels frequently. Runs a consulting firm.',
      documents: [],
      createdAt: new Date().toISOString(),
      isArchived: false,
    },
    {
      id: '5',
      name: 'Meera Reddy',
      propertyName: 'Park View 5E',
      propertyType: 'residential',
      monthlyRent: 16000,
      securityDeposit: 32000,
      startDate: '2024-05-20',
      startMeterReading: '1680',
      phoneNumber: '+919876543214',
      notes: 'Artist, quiet tenant. Works from home as a freelance designer.',
      documents: [],
      createdAt: new Date().toISOString(),
      isArchived: false,
    },
    {
      id: '6',
      name: 'Arun Verma',
      propertyName: 'Hill Top 6F',
      propertyType: 'residential',
      monthlyRent: 14000,
      securityDeposit: 28000,
      startDate: '2024-06-05',
      startMeterReading: '1320',
      phoneNumber: '+919876543215',
      notes: 'Retired teacher, very organized. Enjoys gardening and reading.',
      documents: [],
      createdAt: new Date().toISOString(),
      isArchived: false,
    },
    {
      id: '7',
      name: 'Kavya Iyer',
      propertyName: 'Riverside 7G',
      propertyType: 'residential',
      monthlyRent: 19000,
      securityDeposit: 38000,
      startDate: '2024-07-15',
      startMeterReading: '1850',
      phoneNumber: '+919876543216',
      notes: 'Doctor, works night shifts. Very punctual with payments.',
      documents: [],
      createdAt: new Date().toISOString(),
      isArchived: false,
    },
    {
      id: '8',
      name: 'Suresh Menon',
      propertyName: 'Downtown 8H',
      propertyType: 'commercial',
      monthlyRent: 25000,
      securityDeposit: 50000,
      startDate: '2024-08-01',
      startMeterReading: '2400',
      phoneNumber: '+919876543217',
      notes: 'Software engineer, works from home. Runs a tech startup.',
      documents: [],
      createdAt: new Date().toISOString(),
      isArchived: false,
    },
    // Archived tenants for testing
    {
      id: '9',
      name: 'Lakshmi Nair',
      propertyName: 'Mountain View 9I',
      propertyType: 'residential',
      monthlyRent: 17000,
      securityDeposit: 34000,
      startDate: '2023-09-01',
      startMeterReading: '1100',
      phoneNumber: '+919876543218',
      notes: 'Former tenant - moved to another city for better job opportunity.',
      documents: [],
      createdAt: new Date().toISOString(),
      isArchived: true,
      closingDate: '2024-12-31',
      closingNotes: 'Tenant moved to Bangalore for a senior position at a tech company. Property was left in excellent condition. All outstanding payments cleared.',
    },
    {
      id: '10',
      name: 'Ramesh Gupta',
      propertyName: 'Business Plaza 10J',
      propertyType: 'commercial',
      monthlyRent: 28000,
      securityDeposit: 56000,
      startDate: '2023-06-15',
      startMeterReading: '1800',
      phoneNumber: '+919876543219',
      notes: 'Former business tenant - company relocated to larger office.',
      documents: [],
      createdAt: new Date().toISOString(),
      isArchived: true,
      closingDate: '2024-11-30',
      closingNotes: 'Company relocated to a larger office space in the business district. All outstanding payments cleared. Property maintained well.',
    },
  ];

  const dummyLogs: RentLog[] = [
    // January 2025 - All active tenants
    {
      id: '1',
      tenantId: '1',
      tenantName: 'Priya Sharma',
      date: '2025-01-31',
      rentPaid: 15000,
      previousMeterReading: 1250,
      currentMeterReading: 1380,
      units: 130,
      unitPrice: 8,
      meterBill: 1040,
      total: 16040,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'January payment received on time',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '2',
      tenantId: '2',
      tenantName: 'Rajesh Kumar',
      date: '2025-01-31',
      rentPaid: 12000,
      previousMeterReading: 980,
      currentMeterReading: 1095,
      units: 115,
      unitPrice: 8,
      meterBill: 920,
      total: 12920,
      collector: 'Jane Smith',
      paymentMode: 'online',
      notes: 'January payment - online transfer',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '3',
      tenantId: '3',
      tenantName: 'Anjali Patel',
      date: '2025-01-31',
      rentPaid: 18000,
      previousMeterReading: 1450,
      currentMeterReading: 1620,
      units: 170,
      unitPrice: 8,
      meterBill: 1360,
      total: 19360,
      collector: 'Mike Johnson',
      paymentMode: 'cash',
      notes: 'January payment - family discount applied',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '4',
      tenantId: '4',
      tenantName: 'Vikram Singh',
      date: '2025-01-31',
      rentPaid: 22000,
      previousMeterReading: 2100,
      currentMeterReading: 2280,
      units: 180,
      unitPrice: 8,
      meterBill: 1440,
      total: 23440,
      collector: 'Sarah Wilson',
      paymentMode: 'online',
      notes: 'January payment - business expense',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '5',
      tenantId: '5',
      tenantName: 'Meera Reddy',
      date: '2025-01-31',
      rentPaid: 16000,
      previousMeterReading: 1680,
      currentMeterReading: 1820,
      units: 140,
      unitPrice: 8,
      meterBill: 1120,
      total: 17120,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'January payment - artist studio',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '6',
      tenantId: '6',
      tenantName: 'Arun Verma',
      date: '2025-01-31',
      rentPaid: 14000,
      previousMeterReading: 1320,
      currentMeterReading: 1450,
      units: 130,
      unitPrice: 8,
      meterBill: 1040,
      total: 15040,
      collector: 'Jane Smith',
      paymentMode: 'online',
      notes: 'January payment - retired teacher',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '7',
      tenantId: '7',
      tenantName: 'Kavya Iyer',
      date: '2025-01-31',
      rentPaid: 19000,
      previousMeterReading: 1850,
      currentMeterReading: 2000,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 20200,
      collector: 'Mike Johnson',
      paymentMode: 'cash',
      notes: 'January payment - doctor night shift',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '8',
      tenantId: '8',
      tenantName: 'Suresh Menon',
      date: '2025-01-31',
      rentPaid: 25000,
      previousMeterReading: 2400,
      currentMeterReading: 2580,
      units: 180,
      unitPrice: 8,
      meterBill: 1440,
      total: 26440,
      collector: 'Sarah Wilson',
      paymentMode: 'online',
      notes: 'January payment - tech startup',
      attachments: [],
      createdAt: new Date().toISOString(),
    },

    // February 2025
    {
      id: '9',
      tenantId: '1',
      tenantName: 'Priya Sharma',
      date: '2025-02-28',
      rentPaid: 15000,
      previousMeterReading: 1380,
      currentMeterReading: 1520,
      units: 140,
      unitPrice: 8,
      meterBill: 1120,
      total: 16120,
      collector: 'John Doe',
      paymentMode: 'online',
      notes: 'February payment - online transfer',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '10',
      tenantId: '2',
      tenantName: 'Rajesh Kumar',
      date: '2025-02-28',
      rentPaid: 12000,
      previousMeterReading: 1095,
      currentMeterReading: 1220,
      units: 125,
      unitPrice: 8,
      meterBill: 1000,
      total: 13000,
      collector: 'Jane Smith',
      paymentMode: 'cash',
      notes: 'February payment - marketing professional',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '11',
      tenantId: '3',
      tenantName: 'Anjali Patel',
      date: '2025-02-28',
      rentPaid: 18000,
      previousMeterReading: 1620,
      currentMeterReading: 1780,
      units: 160,
      unitPrice: 8,
      meterBill: 1280,
      total: 19280,
      collector: 'Mike Johnson',
      paymentMode: 'online',
      notes: 'February payment - family with kids',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '12',
      tenantId: '4',
      tenantName: 'Vikram Singh',
      date: '2025-02-28',
      rentPaid: 22000,
      previousMeterReading: 2280,
      currentMeterReading: 2450,
      units: 170,
      unitPrice: 8,
      meterBill: 1360,
      total: 23360,
      collector: 'Sarah Wilson',
      paymentMode: 'cash',
      notes: 'February payment - consulting business',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '13',
      tenantId: '5',
      tenantName: 'Meera Reddy',
      date: '2025-02-28',
      rentPaid: 16000,
      previousMeterReading: 1820,
      currentMeterReading: 1950,
      units: 130,
      unitPrice: 8,
      meterBill: 1040,
      total: 17040,
      collector: 'John Doe',
      paymentMode: 'online',
      notes: 'February payment - freelance designer',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '14',
      tenantId: '6',
      tenantName: 'Arun Verma',
      date: '2025-02-28',
      rentPaid: 14000,
      previousMeterReading: 1450,
      currentMeterReading: 1580,
      units: 130,
      unitPrice: 8,
      meterBill: 1040,
      total: 15040,
      collector: 'Jane Smith',
      paymentMode: 'cash',
      notes: 'February payment - retired teacher',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '15',
      tenantId: '7',
      tenantName: 'Kavya Iyer',
      date: '2025-02-28',
      rentPaid: 19000,
      previousMeterReading: 2000,
      currentMeterReading: 2150,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 20200,
      collector: 'Mike Johnson',
      paymentMode: 'online',
      notes: 'February payment - doctor',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '16',
      tenantId: '8',
      tenantName: 'Suresh Menon',
      date: '2025-02-28',
      rentPaid: 25000,
      previousMeterReading: 2580,
      currentMeterReading: 2750,
      units: 170,
      unitPrice: 8,
      meterBill: 1360,
      total: 26360,
      collector: 'Sarah Wilson',
      paymentMode: 'cash',
      notes: 'February payment - tech startup',
      attachments: [],
      createdAt: new Date().toISOString(),
    },

    // March 2025
    {
      id: '17',
      tenantId: '1',
      tenantName: 'Priya Sharma',
      date: '2025-03-31',
      rentPaid: 15000,
      previousMeterReading: 1520,
      currentMeterReading: 1670,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 16200,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'March payment - software engineer',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '18',
      tenantId: '2',
      tenantName: 'Rajesh Kumar',
      date: '2025-03-31',
      rentPaid: 12000,
      previousMeterReading: 1220,
      currentMeterReading: 1350,
      units: 130,
      unitPrice: 8,
      meterBill: 1040,
      total: 13040,
      collector: 'Jane Smith',
      paymentMode: 'online',
      notes: 'March payment - marketing professional',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '19',
      tenantId: '3',
      tenantName: 'Anjali Patel',
      date: '2025-03-31',
      rentPaid: 18000,
      previousMeterReading: 1780,
      currentMeterReading: 1950,
      units: 170,
      unitPrice: 8,
      meterBill: 1360,
      total: 19360,
      collector: 'Mike Johnson',
      paymentMode: 'cash',
      notes: 'March payment - family',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '20',
      tenantId: '4',
      tenantName: 'Vikram Singh',
      date: '2025-03-31',
      rentPaid: 22000,
      previousMeterReading: 2450,
      currentMeterReading: 2620,
      units: 170,
      unitPrice: 8,
      meterBill: 1360,
      total: 23360,
      collector: 'Sarah Wilson',
      paymentMode: 'online',
      notes: 'March payment - consulting business',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '21',
      tenantId: '5',
      tenantName: 'Meera Reddy',
      date: '2025-03-31',
      rentPaid: 16000,
      previousMeterReading: 1950,
      currentMeterReading: 2080,
      units: 130,
      unitPrice: 8,
      meterBill: 1040,
      total: 17040,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'March payment - artist',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '22',
      tenantId: '6',
      tenantName: 'Arun Verma',
      date: '2025-03-31',
      rentPaid: 14000,
      previousMeterReading: 1580,
      currentMeterReading: 1710,
      units: 130,
      unitPrice: 8,
      meterBill: 1040,
      total: 15040,
      collector: 'Jane Smith',
      paymentMode: 'online',
      notes: 'March payment - retired teacher',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '23',
      tenantId: '7',
      tenantName: 'Kavya Iyer',
      date: '2025-03-31',
      rentPaid: 19000,
      previousMeterReading: 2150,
      currentMeterReading: 2300,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 20200,
      collector: 'Mike Johnson',
      paymentMode: 'cash',
      notes: 'March payment - doctor',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '24',
      tenantId: '8',
      tenantName: 'Suresh Menon',
      date: '2025-03-31',
      rentPaid: 25000,
      previousMeterReading: 2750,
      currentMeterReading: 2920,
      units: 170,
      unitPrice: 8,
      meterBill: 1360,
      total: 26360,
      collector: 'Sarah Wilson',
      paymentMode: 'online',
      notes: 'March payment - tech startup',
      attachments: [],
      createdAt: new Date().toISOString(),
    },

    // Archived tenant rent logs - Complete history for Lakshmi Nair
    {
      id: '25',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-01-31',
      rentPaid: 17000,
      previousMeterReading: 1100,
      currentMeterReading: 1250,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'January 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '26',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-02-29',
      rentPaid: 17000,
      previousMeterReading: 1250,
      currentMeterReading: 1400,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'Jane Smith',
      paymentMode: 'online',
      notes: 'February 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '27',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-03-31',
      rentPaid: 17000,
      previousMeterReading: 1400,
      currentMeterReading: 1550,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'Mike Johnson',
      paymentMode: 'cash',
      notes: 'March 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '28',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-04-30',
      rentPaid: 17000,
      previousMeterReading: 1550,
      currentMeterReading: 1700,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'Sarah Wilson',
      paymentMode: 'online',
      notes: 'April 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '29',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-05-31',
      rentPaid: 17000,
      previousMeterReading: 1700,
      currentMeterReading: 1850,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'May 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '30',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-06-30',
      rentPaid: 17000,
      previousMeterReading: 1850,
      currentMeterReading: 2000,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'Jane Smith',
      paymentMode: 'online',
      notes: 'June 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '31',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-07-31',
      rentPaid: 17000,
      previousMeterReading: 2000,
      currentMeterReading: 2150,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'Mike Johnson',
      paymentMode: 'cash',
      notes: 'July 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '32',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-08-31',
      rentPaid: 17000,
      previousMeterReading: 2150,
      currentMeterReading: 2300,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'Sarah Wilson',
      paymentMode: 'online',
      notes: 'August 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '33',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-09-30',
      rentPaid: 17000,
      previousMeterReading: 2300,
      currentMeterReading: 2450,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'September 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '34',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-10-31',
      rentPaid: 17000,
      previousMeterReading: 2450,
      currentMeterReading: 2600,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'Jane Smith',
      paymentMode: 'online',
      notes: 'October 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '35',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-11-30',
      rentPaid: 17000,
      previousMeterReading: 2600,
      currentMeterReading: 2750,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'Mike Johnson',
      paymentMode: 'cash',
      notes: 'November 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '36',
      tenantId: '9',
      tenantName: 'Lakshmi Nair',
      date: '2024-12-31',
      rentPaid: 17000,
      previousMeterReading: 2750,
      currentMeterReading: 2900,
      units: 150,
      unitPrice: 8,
      meterBill: 1200,
      total: 18200,
      collector: 'Sarah Wilson',
      paymentMode: 'online',
      notes: 'December 2024 payment - Final payment before moving',
      attachments: [],
      createdAt: new Date().toISOString(),
    },

    // Archived tenant rent logs - Complete history for Ramesh Gupta
    {
      id: '37',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2023-07-31',
      rentPaid: 28000,
      previousMeterReading: 1800,
      currentMeterReading: 2000,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'July 2023 payment - Business startup',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '38',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2023-08-31',
      rentPaid: 28000,
      previousMeterReading: 2000,
      currentMeterReading: 2200,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Jane Smith',
      paymentMode: 'online',
      notes: 'August 2023 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '39',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2023-09-30',
      rentPaid: 28000,
      previousMeterReading: 2200,
      currentMeterReading: 2400,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Mike Johnson',
      paymentMode: 'cash',
      notes: 'September 2023 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '40',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2023-10-31',
      rentPaid: 28000,
      previousMeterReading: 2400,
      currentMeterReading: 2600,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Sarah Wilson',
      paymentMode: 'online',
      notes: 'October 2023 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '41',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2023-11-30',
      rentPaid: 28000,
      previousMeterReading: 2600,
      currentMeterReading: 2800,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'November 2023 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '42',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2023-12-31',
      rentPaid: 28000,
      previousMeterReading: 2800,
      currentMeterReading: 3000,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Jane Smith',
      paymentMode: 'online',
      notes: 'December 2023 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '43',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2024-01-31',
      rentPaid: 28000,
      previousMeterReading: 3000,
      currentMeterReading: 3200,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Mike Johnson',
      paymentMode: 'cash',
      notes: 'January 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '44',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2024-02-29',
      rentPaid: 28000,
      previousMeterReading: 3200,
      currentMeterReading: 3400,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Sarah Wilson',
      paymentMode: 'online',
      notes: 'February 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '45',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2024-03-31',
      rentPaid: 28000,
      previousMeterReading: 3400,
      currentMeterReading: 3600,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'March 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '46',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2024-04-30',
      rentPaid: 28000,
      previousMeterReading: 3600,
      currentMeterReading: 3800,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Jane Smith',
      paymentMode: 'online',
      notes: 'April 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '47',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2024-05-31',
      rentPaid: 28000,
      previousMeterReading: 3800,
      currentMeterReading: 4000,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Mike Johnson',
      paymentMode: 'cash',
      notes: 'May 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '48',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2024-06-30',
      rentPaid: 28000,
      previousMeterReading: 4000,
      currentMeterReading: 4200,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Sarah Wilson',
      paymentMode: 'online',
      notes: 'June 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '49',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2024-07-31',
      rentPaid: 28000,
      previousMeterReading: 4200,
      currentMeterReading: 4400,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'July 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '50',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2024-08-31',
      rentPaid: 28000,
      previousMeterReading: 4400,
      currentMeterReading: 4600,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Jane Smith',
      paymentMode: 'online',
      notes: 'August 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '51',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2024-09-30',
      rentPaid: 28000,
      previousMeterReading: 4600,
      currentMeterReading: 4800,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Mike Johnson',
      paymentMode: 'cash',
      notes: 'September 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '52',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2024-10-31',
      rentPaid: 28000,
      previousMeterReading: 4800,
      currentMeterReading: 5000,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'Sarah Wilson',
      paymentMode: 'online',
      notes: 'October 2024 payment',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
    {
      id: '53',
      tenantId: '10',
      tenantName: 'Ramesh Gupta',
      date: '2024-11-30',
      rentPaid: 28000,
      previousMeterReading: 5000,
      currentMeterReading: 5200,
      units: 200,
      unitPrice: 8,
      meterBill: 1600,
      total: 29600,
      collector: 'John Doe',
      paymentMode: 'cash',
      notes: 'November 2024 payment - Final payment before relocation',
      attachments: [],
      createdAt: new Date().toISOString(),
    },
  ];

  return {
    tenants: dummyTenants,
    rentLogs: dummyLogs,
    rentCollectors: dummyCollectors,
  };
}

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [state, dispatch] = useReducer(appReducer, initialState);

  // Load data from localStorage on mount
  useEffect(() => {
    const savedTenants = loadFromStorage<Tenant[]>('tenants', []);
    const savedRentLogs = loadFromStorage<RentLog[]>('rentLogs', []);
    const savedCollectors = loadFromStorage<RentCollector[]>('rentCollectors', []);
    const savedSettings = loadFromStorage<AppSettings>('settings', { defaultUnitPrice: 8 });

    dispatch({ type: 'SET_TENANTS', payload: savedTenants });
    dispatch({ type: 'SET_RENT_LOGS', payload: savedRentLogs });
    dispatch({ type: 'SET_RENT_COLLECTORS', payload: savedCollectors });
    dispatch({ type: 'UPDATE_SETTINGS', payload: savedSettings });
  }, []);

  // Save data to localStorage whenever state changes
  useEffect(() => {
    saveToStorage('tenants', state.tenants);
  }, [state.tenants]);

  useEffect(() => {
    saveToStorage('rentLogs', state.rentLogs);
  }, [state.rentLogs]);

  useEffect(() => {
    saveToStorage('rentCollectors', state.rentCollectors);
  }, [state.rentCollectors]);

  useEffect(() => {
    saveToStorage('settings', state.settings);
  }, [state.settings]);

  return (
    <AppContext.Provider value={{ state, dispatch }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useApp must be used within an AppProvider');
  }
  return context;
}